Initial commit
eastgenomics/automated-archiving pull request #1
Opened 2022-01-07 12:32 UTC by JasonLing95

2022-01-07 12:32 UTC, pep8speaks commented
Hello @JasonLing95! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`main.py`](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py):

> [Line 268:80](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L268): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 79 characters)
> [Line 289:80](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L289): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 290:80](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L290): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 464:80](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L464): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)

2022-01-07 14:43 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 0 of 5 files reviewed, 23 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[main.py, line 1 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsokpOO90d_MwlUUBpJ:-MsokpOP0rbZU8LmC7Bv:b2fm8ff) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L1)):*
> ```Python
> import os
> ```

a docstring here to explain what the script does would be good
___
*[main.py, line 13 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsokvIFBzQjxCNt8XbG:-MsokvIFBzQjxCNt8XbH:b-rkjuq3) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L13)):*
> ```Python
> from helper import get_logger
> 
> log = get_logger("main log")
> ```

minor thing but I think its best practice to capitalise anything you declare outside of a function as a global/constant in capitals, as it is then explicit throughout you are referring to a global (like you have below for `PROJECT_52` etc.)
___
*[main.py, line 35 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsolvvD0OqgL3l6I0tt:-MsolvvE1KBjtOJFx_Ns:b-snmq3e) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L35)):*
> ```Python
>         index: index for which proj in lists (below)
>         data: list of projs / dirs to be archived
>         error: (for dxpy token) error msg
> ```

is this a returned object from a dxpy call? either adding types to your docstring for inputs/outputs or using [type hints](https://www.python.org/dev/peps/pep-0484/) could be useful to make this clearer
___
*[main.py, line 36 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsolkY66ZRuEm_lny1Q:-MsolkY66ZRuEm_lny1R:b-kuaqcj) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L36)):*
> ```Python
>         data: list of projs / dirs to be archived
>         error: (for dxpy token) error msg
>         alert: (for dxpy token)
> ```

could you clarify what alert is for? Not sure I understand from the below `if alert`
___
*[main.py, line 69 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsomVGV5k3PvmRCEx7o:-MsomVGV5k3PvmRCEx7p:b4dtlkm) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L69)):*
> ```Python
>             try:
>                 error = error.error_message()
>             except Exception as _:
> ```

whats the logic for handling any exception and not caring what it is? a comment might help with this as I might just be missing something related to dxpy
___
*[main.py, line 92 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsonLN0-SUwuH3bfm26:-MsonLN0-SUwuH3bfm27:bozq9z5) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L92)):*
> ```Python
>                 log.error(f'Error Code From Slack: {error_code}')
>         else:
>             response = requests.post(
> ```

should this have some level of retrying in case of network / slack api issues? i.e. https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/
___
*[main.py, line 118 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsonTy84DEGwTLp6Pez:-MsonTy84DEGwTLp6Pf-:b-966k7v) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L118)):*
> ```Python
> def read_or_new_pickle(path):
>     """
>     Read stored pickle memory for the script
> ```

what is it you are pickling?
___
*[main.py, line 131 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsonYqO4ERLh3vEbj2Y:-MsonYqO4ERLh3vEbj2Z:bxpxtcb) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L131)):*
> ```Python
>         with open(path, 'rb') as f:
>             b = pickle.load(f)
>     except Exception as e:
> ```

what could be the exceptions here? is it if the file doesn't exist that you want to create a new one? this will also catch permissions issues as well which would be ambiguous.

if this is just to handle the file not existing I think it would be best to explictly check if the file exists first load it if it does (either `os.path.exists()` or `Path().is_file()` from pathlib would do it)
___
*[main.py, line 138 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsooHfF3KrVgSLgdQou:-MsooHfG1OevnDOgR2QC:byvamqa) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L138)):*
> ```Python
> 
>         with open(path, 'rb') as f:
>             b = pickle.load(f)
> ```

single character variable names should be avoided
___
*[main.py, line 170 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Msop4id4S5bvchAsmu9:-Msop4id4S5bvchAsmuA:b-c6bcjq) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L170)):*
> ```Python
> 
>     Returns:
>         Boolean: True if there are no files which
> ```

returning True for not finding files from a function named `find_files()` seems the wrong way round, should it not return False if non are found?
___
*[main.py, line 179 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsooZdXAG2Ui9wCO6XH:-MsooZdXAG2Ui9wCO6XI:b-xxh5oc) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L179)):*
> ```Python
>         project=proj,
>         folder=dir,
>         modified_after=f'-{days}d'
> ```

do you know how it identifies if a file has been modified? I think that would just be created, since if file ids are unique to a hash of a file (i.e if a file changes then the file id will be different). Does this also pick up if a file is tagged or had properties added which would delay archiving?
___
*[main.py, line 218 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsopJ024yJ8S_J4txDi:-MsopJ024yJ8S_J4txDj:b-m27nif) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L218)):*
> ```Python
>             )
> 
>         log.info('End of script')
> ```

is this needed?
___
*[main.py, line 224 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsopWJy8w97Z-3EPu1E:-MsopWJy8w97Z-3EPu1F:bivwjrb) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L224)):*
> ```Python
> def remove_proj_tag(proj):
>     """
>     Function to remove tag 'no-archive' for project
> ```

can you add to this doc string what the purpose of the tag is, and when it would be removed by this function
___
*[main.py, line 233 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsopP8_Epz23Qj-6IAB:-MsopP8a3b5h_i9uu0-W:b1hpv8l) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L233)):*
> ```Python
>     """
> 
>     r = dx.api.project_remove_tags(
> ```

single character variable name
___
*[main.py, line 238 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsopeR5-8DbhqaNiYPx:-MsopeR5-8DbhqaNiYPy:b-gazqkt) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L238)):*
> ```Python
> 
> 
> def code_a():
> ```

this function name is confusing, can it be more specific than `_a` and `_b`?
___
*[main.py, line 245 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Msopl-03dSfBSWnv_VI:-Msopl-03dSfBSWnv_VJ:b-ocd8py) ( [...]

2022-01-10 23:05 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 0 of 5 files reviewed, 23 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[main.py, line 245 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Msopl-03dSfBSWnv_VI:-Mt58Glg8OQLd6w3Jm-P:b-o19ljm) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L245)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

whats the purpose of it being special?
</blockquote></details>

this list will include projects / directories which have been tagged to skip archiving but has not been modified for quite a while (inactive), thus will be specially mentioned in Slack
___
*[main.py, line 260 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Msopx-m2b0uckaPogBJ:-Mt58mND7NF5YsvRxY_Y:b-896fix) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L260)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

comment to explain what this does
</blockquote></details>

Done.
___
*[main.py, line 266 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Msoq4YY0ecrwBosXYXe:-Mt3-h321jIxpnCxqeC0:bultk2y) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L266)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

just checking are these exlcuded because we aren't archiving the whole project?
</blockquote></details>

yes, since staging52 and staging53 are both giant projects with directories constantly being uploaded to it, we will only be archiving directories in this projects which we no longer need
___
*[main.py, line 268 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsoxiIC3IRQRrtf4dl2:-Mt5AIiF4yG1IhTIdBDh:b-896fix) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L268)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

pep8 line length, can it be something like this:

```   
 old_enough_projects_dict = {
        k: v for k, v in old_enough_projects_dict.items() \
        if k not in excluded_list and k not in archive_pickle['archived']
    }
```
</blockquote></details>

Done.
___
*[main.py, line 311 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsoygGF2_ixeKMEy6UT:-Mt5ALLE7V2-taYvuj3B:b-1cbtq9) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L311)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

will this just remove any `no-archive` tag? what is the purpose of the tag? is there any differentiate between 'never archive this file' vs 'dont archive this file for X period of time'?
</blockquote></details>

There will only be one tag 'no-archive' which will skip archiving and the folders or projects tagged will not be archived for X months. We could introduce a 'never-archive' tag to skip archiving forever
___
*[main.py, line 328 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsozBQ50MRpjwkB5kh2:-Mt5E4XB6RPrmMRI9S6Z:b-896fix) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L328)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this looks  nearly the same as `old_enough_53`, can it be dryer and be a function?
</blockquote></details>

Done.
___
*[main.py, line 402 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsozRIB7kMVm4XGDfEf:-Mt5E5tx3TeslWTvRo9T:b-896fix) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L402)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

similar comments to those in `code_a()`
</blockquote></details>

Done.
___
*[README.md, line 34 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsozZnu2zxGnvO6V76o:-Mt5E7k5D5XSDN4l8r-8:bfpow8f) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/README.md#L34)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this not also need `--network-host` to access Slack / dx?
</blockquote></details>

not needed for slack post request


<!-- Sent from Reviewable.io -->

2022-01-10 23:49 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 0 of 5 files reviewed, 23 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[main.py, line 13 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsokvIFBzQjxCNt8XbG:-Mt5EGnL6SAlXEubu8BN:b-ny7r1k) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L13)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

minor thing but I think its best practice to capitalise anything you declare outside of a function as a global/constant in capitals, as it is then explicit throughout you are referring to a global (like you have below for `PROJECT_52` etc.)
</blockquote></details>

the log is a function from the helper.py, either log.info or log.error so it won't be a static value.
___
*[main.py, line 35 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsolvvD0OqgL3l6I0tt:-Mt5ETp23mHc3srXTBNn:b-l7w972) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L35)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is this a returned object from a dxpy call? either adding types to your docstring for inputs/outputs or using [type hints](https://www.python.org/dev/peps/pep-0484/) could be useful to make this clearer
</blockquote></details>

the post_to_slack function will be used for sending notification to notify what files will be archived in the next script run + if dxpy login failed. so to differentiate between the two calls: an alert Boolean is added. alert = True for dxpy auth message, everything else is alert=False (default). Added more comments to the function
___
*[main.py, line 36 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsolkY66ZRuEm_lny1Q:-Mt5ExNj4bgXTRwBCdpc:b-qfeido) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L36)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could you clarify what alert is for? Not sure I understand from the below `if alert`
</blockquote></details>

a boolean to differentiate between dxpy auth error message or just another slack notification for to-be-archived files
___
*[main.py, line 69 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsomVGV5k3PvmRCEx7o:-Mt5FCAN2SdsXxWPNSS6:b-cd56fs) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L69)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

whats the logic for handling any exception and not caring what it is? a comment might help with this as I might just be missing something related to dxpy
</blockquote></details>

Forgot what error caused it to return an error object without error_message() which will fail the script. But I can't replicate it in my current local testing, so try-catch removed.
___
*[main.py, line 92 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsonLN0-SUwuH3bfm26:-Mt5FQah-p9hUxgFuKb7:b-b0gd3n) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L92)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

should this have some level of retrying in case of network / slack api issues? i.e. https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/
</blockquote></details>

added 3 retry with a wait time of 0.5, 1, 2 in-between (backoff_factor=1)
___
*[main.py, line 118 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsonTy84DEGwTLp6Pez:-Mt5N7IK9Y1xahqh5fJ-:bdqemkp) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L118)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what is it you are pickling?
</blockquote></details>

this allows the script to remember which files to be archived the next time it runs
___
*[main.py, line 131 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsonYqO4ERLh3vEbj2Y:-Mt5NZ7x40t47PymmvKH:b-896fix) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L131)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what could be the exceptions here? is it if the file doesn't exist that you want to create a new one? this will also catch permissions issues as well which would be ambiguous.

if this is just to handle the file not existing I think it would be best to explictly check if the file exists first load it if it does (either `os.path.exists()` or `Path().is_file()` from pathlib would do it)
</blockquote></details>

Done.
___
*[main.py, line 138 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsooHfF3KrVgSLgdQou:-Mt5NZta1d0u3m1eW-ou:b-rcu9aq) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L138)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

single character variable names should be avoided
</blockquote></details>

edited
___
*[main.py, line 170 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Msop4id4S5bvchAsmu9:-Mt5Naw-778N28hndRLQ:b-rcu9aq) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L170)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

returning True for not finding files from a function named `find_files()` seems the wrong way round, should it not return False if non are found?
</blockquote></details>

edited
___
*[main.py, line 179 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsooZdXAG2Ui9wCO6XH:-Mt5Nd0G8WvgpLRLm9Vi:b3tp60d) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L179)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

do you know how it identifies if a file has been modified? I think that would just be created, since if file ids are unique to a hash of a file (i.e if a file changes then the file id will be different). Does this also pick up if a file is tagged or had properties added which would delay archiving?
</blockquote></details>

changed the function to check if the directory in staging52/53 have a 002 bring created + if the 002 has been inactive in the past X month
___
*[main.py, line 218 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsopJ024yJ8S_J4txDi:-Mt5NzB75wHgqkyqM2j0:b7upvdm) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L218)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is this needed?
</blockquote></details>

I think it's more understandable if we ever need to read the log to debug to know if script start and stop
___
*[main.py, line 224 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsopWJy8w97Z-3EPu1E:-Mt5OF0F-xpKP6lYL5rt:b-896fix) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L224)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you add to this doc string what the purpose of the tag is, and when it would be removed by this function
</blockquote></details>

Done.
___
*[main.py, line 233 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsopP8_Epz23Qj-6IAB:-Mt5OFdyBJz0_JakP_oS:b-rcu9aq) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L [...]

2022-01-10 23:52 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 0 of 5 files reviewed, 23 unresolved discussions (waiting on @jethror1)

___
*[main.py, line 1 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsokpOO90d_MwlUUBpJ:-Mt5P9hTEG7ZT8Gx0hhI:b-896fix) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L1)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

a docstring here to explain what the script does would be good
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-11 22:29 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 0 of 5 files reviewed, 18 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[helper.py, line 27 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtA7eDO3F68mqDD513J:-MtA7eDO3F68mqDD513K:b-mwgvb0) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/helper.py#L27)):*
> ```Python
> 
> def get_file_handler():
>     file_handler = TimedRotatingFileHandler(LOG_FILE, when='midnight')
> ```

does this mean the log is overwritten everyday? should we have it longer / write daily and have a rolling max number (i.e. a week)?
___
*[main.py, line 92 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsonLN0-SUwuH3bfm26:-MtAAOhBEk4piXIjstmz:b93g7a6) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L92)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

added 3 retry with a wait time of 0.5, 1, 2 in-between (backoff_factor=1)
</blockquote></details>

is that in seconds? Maybe slightly more / more retries would be good, this can wait on an intermittent outage since its running infrequently, which would be better than it failing
___
*[main.py, line 118 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsonTy84DEGwTLp6Pez:-MtAAfrk8VJKryTk5TNo:bn4913c) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L118)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this allows the script to remember which files to be archived the next time it runs
</blockquote></details>

ah okay, so is the idea that it runs one month and tells us what is going to be archived, then the next month it archives what was previously stored? That's sensible if so, just wasn't sure :) 
___
*[main.py, line 311 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsoygGF2_ixeKMEy6UT:-MtADhPG0KeIaNwmVXbe:b-jyfh35) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L311)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

There will only be one tag 'no-archive' which will skip archiving and the folders or projects tagged will not be archived for X months. We could introduce a 'never-archive' tag to skip archiving forever
</blockquote></details>

Does this mean if something is tagged `no-archive` and the script is set to 2 months, that it will allow a file to keep the tag for 2 months, then will remove it and archive it?

If so, have you tested this works (my brain isn't wanting to understand all of the code and figure it out myself)
___
*[main.py, line 100 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtA9ru00ofCizPjAfd7:-MtA9ru00ofCizPjAfd8:b-rxlhw8) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L100)):*
> ```Python
>             if response['ok']:
>                 log.info(f'POST request to channel #{channel} successful')
>             else:
> ```

not sure if it is essential for v1 but we could have a fallback here to alert us via a helpdesk ticket, probably is a good idea as if it isn't able to send slack notifications its either an issue with connectivity from the server to slack or the slack token, and since more is now replying on the slack notifications it would be good to know if it is down
___
*[main.py, line 371 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtACcvz3KsB5_w39dBc:-MtACcvz3KsB5_w39dBd:b-ugn6wd) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L371)):*
> ```Python
>     If there is 'never-archive', return
> 
>     If there is 'no-archive' tag in any file within the directory,
> ```

does this mean if one file is tagged to never archive, then everything in the same dir and child ones will never be archived? 
@mattgarner is this behavior what we want (I'm not even sure what would be best), just wondering if we ever would have random things we wouldn't want to archive (i.e. multiqc reports so they would always would be available and are small enough to not care about), but then everything else in the same dirs would never be archived
___
*[main.py, line 408 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtADPR10upoPTCYLNrP:-MtADPR10upoPTCYLNrQ:bfcm7qw) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L408)):*
> ```Python
>     else:
>         log.info(f'archiving staging{num}: {dir}')
>         # dx.api.project_archive(
> ```

not needed?



_Code quote:_
```Python
        # dx.api.project_archive(
        #     proj, input_params={'folder': dir})
```
___
*[main.py, line 421 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtADWKoE2hPGqUuSnw-:-MtADWKoE2hPGqUuSnw0:b-2wsom3) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L421)):*
> ```Python
>     """
> 
>     log.info('Running Code A')
> ```

update to match new function name
___
*[main.py, line 549 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtAENg2--fxL9Dl2b9q:-MtAENg3CVLcjk60sCKf:b-yvxbmj) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L549)):*
> ```Python
>         pickle.dump(archive_pickle, f)
> 
>     log.info('End of Code A')
> ```

update to match function name
___
*[main.py, line 563 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtAETeb9aOLPfhUtZUP:-MtAETeb9aOLPfhUtZUQ:b-yvxbmj) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L563)):*
> ```Python
>     """
> 
>     log.info('Running Code B')
> ```

update to match function name
___
*[main.py, line 589 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtAEaBBBdHBSdb5JsqK:-MtAEaBBBdHBSdb5JsqL:bxmos3h) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L589)):*
> ```Python
>             else:
>                 log.info(f'archiving {id}')
>                 # dx.api.project_archive(proj)
> ```

commented to remove?
___
*[main.py, line 623 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtAExPt2rdpF-QocCbJ:-MtAExPt2rdpF-QocCbK:b-yvxbmj) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L623)):*
> ```Python
>         pickle.dump(archive_pickle, f)
> 
>     log.info('End of Code B')
> ```

update to match function name
___
*[README.md, line 4 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtAFWb89MWICA5ZKbEt:-MtAFWb89MWICA5ZKbEu:b-38f7y) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/README.md#L4)):*
> ```Markdown
> 
> ## What does the script do
> Check for 002, 003 projects, directories in staging52 and staging53 which are not modified for the last X months (inactive). Compile all archivable into a list and send Slack notification to notify all to-be-archived files in the next run. Tag `no-archive` to skip archiving.
> ```

more info on tags, i.e. what adding the `no-archive` behaviour is, and also add about `never-archive`
___
*[README.md, line 15 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtAF86w43-WT3_gEHeF:-MtAF86w43-WT3_gEHeG:bunv011) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/ [...]

2022-01-12 17:41 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 0 of 5 files reviewed, 18 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[helper.py, line 27 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtA7eDO3F68mqDD513J:-MtD0BSO53VHzdJyZdtm:b-1l2xj6) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/helper.py#L27)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this mean the log is overwritten everyday? should we have it longer / write daily and have a rolling max number (i.e. a week)?
</blockquote></details>

everytime it runs, it will generate a new file with the filename dated.today() so that it's easier to track the log by day
___
*[main.py, line 92 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsonLN0-SUwuH3bfm26:-MtEMmNy5bLBZcX6N4pc:b-q3phar) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L92)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is that in seconds? Maybe slightly more / more retries would be good, this can wait on an intermittent outage since its running infrequently, which would be better than it failing
</blockquote></details>

adjusted to 5 retries with backoff_factor=10 which translate to (5, 10, 20, 40, 80 seconds) https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/
___
*[main.py, line 100 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtA9ru00ofCizPjAfd7:-MtE0jpo0lKLgl1QqKKF:bo08ccw) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L100)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

not sure if it is essential for v1 but we could have a fallback here to alert us via a helpdesk ticket, probably is a good idea as if it isn't able to send slack notifications its either an issue with connectivity from the server to slack or the slack token, and since more is now replying on the slack notifications it would be good to know if it is down
</blockquote></details>

added server_mail_function. send mail if Slack API token failed or server connectivity failure


<!-- Sent from Reviewable.io -->

2022-01-12 18:18 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 0 of 5 files reviewed, 18 unresolved discussions (waiting on @JasonLing95, @jethror1, and @mattgarner)

___
*[main.py, line 118 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsonTy84DEGwTLp6Pez:-MtENO6MBgg3ckHUW-bL:b-sawli4) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L118)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ah okay, so is the idea that it runs one month and tells us what is going to be archived, then the next month it archives what was previously stored? That's sensible if so, just wasn't sure :) 
</blockquote></details>

yes. it will run (1st run) - get all projs and notify on Slack. People then have time to do the tagging during interval. Next run (2nd run), it starts archiving and skip through those being tagged
___
*[main.py, line 311 at r1](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MsoygGF2_ixeKMEy6UT:-MtER_VV7HfcYzJV8UCJ:bvez7cb) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/e0de7a062310551c166a19b0bf01c230994d24f7/main.py#L311)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Does this mean if something is tagged `no-archive` and the script is set to 2 months, that it will allow a file to keep the tag for 2 months, then will remove it and archive it?

If so, have you tested this works (my brain isn't wanting to understand all of the code and figure it out myself)
</blockquote></details>

yes. If a person tag a proj, the modified date for the proj is changed to datetime.today(). Since our script only detect for proj older than X month (2 in this case), the proj will only show up after 2 month. And the reason behind this scenario is if the person has tagged the proj but has not touch the proj for 2 month (the modified date didn't change since the tagging happens). If he/she has been working the project (actively), the modified date will change continuously so it wouldn't show up in our script 
___
*[main.py, line 371 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtACcvz3KsB5_w39dBc:-MtENkpL4psQ3UE5kTYg:b-tr5i4k) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L371)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this mean if one file is tagged to never archive, then everything in the same dir and child ones will never be archived? 
@mattgarner is this behavior what we want (I'm not even sure what would be best), just wondering if we ever would have random things we wouldn't want to archive (i.e. multiqc reports so they would always would be available and are small enough to not care about), but then everything else in the same dirs would never be archived
</blockquote></details>

yes. current script logic: if one file is tagged 'no archive', we skip the whole dir / if tagged 'never-archive', we just ignore the directory (this only applies for staging52 and staging53). However, every time the script run, it will check if the 'never-archive' tag still exist, just in case someone regret it later on. For 'no-archive' tag, if it has been there longer than X month, it will be removed by the script and listed for archiving (Slack) until tagged again. 
___
*[main.py, line 408 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtADPR10upoPTCYLNrP:-MtER34V0yq__srer9lV:bk7qwfo) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L408)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

not needed?
</blockquote></details>

commented just in case I accidentally ran the archiving api. In production this will be un-commented
___
*[main.py, line 421 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtADWKoE2hPGqUuSnw-:-MtERDXh17OJTg7O6bg9:bvnrpcm) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L421)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

update to match new function name
</blockquote></details>

updated
___
*[main.py, line 549 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtAENg2--fxL9Dl2b9q:-MtEVhoy3X-Q7voh1BNt:bvnrpcm) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L549)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

update to match function name
</blockquote></details>

updated
___
*[main.py, line 563 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtAETeb9aOLPfhUtZUP:-MtEVj0p9j0h6b9yMW7R:bvnrpcm) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L563)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

update to match function name
</blockquote></details>

updated
___
*[main.py, line 589 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtAEaBBBdHBSdb5JsqK:-MtEVmfQEtq6F8DYtYvQ:bk7qwfo) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L589)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

commented to remove?
</blockquote></details>

commented just in case I accidentally ran the archiving api. In production this will be un-commented
___
*[main.py, line 623 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtAExPt2rdpF-QocCbJ:-MtEVogG7yY-qgIjFcbR:bvnrpcm) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L623)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

update to match function name
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2022-01-14 10:55 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 0 of 5 files reviewed, 18 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[README.md, line 4 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtAFWb89MWICA5ZKbEt:-MtNCpXn8_TgBBicLOf1:b-4rlok9) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/README.md#L4)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

more info on tags, i.e. what adding the `no-archive` behaviour is, and also add about `never-archive`
</blockquote></details>

added tags in readme
___
*[README.md, line 15 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtAF86w43-WT3_gEHeF:-MtNCsr74lWfw0CYfMJ3:b-rr00hg) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/README.md#L15)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Can you add slightly more to this, i.e. `Period of file being inactive after which to archive (months)`
</blockquote></details>

updated. Separated the config into two: AUTOMATED_MONTH_002 (for 002 projects and others, default 6 months) AND AUTOMATED_MONTH_003 (for 003 projects, 1 month)
___
*[README.md, line 25 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtAFOPYD4RaFCgRQPQM:-MtNDS0X8lN_otSc62Ed:btmsk18) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/README.md#L25)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you add a line to explain the pickle file also so its obvious to anyone else wondering what it is
</blockquote></details>

added a new section Archive Pickle in readme + Script workflow to explain the memory and running workflow


<!-- Sent from Reviewable.io -->

2022-01-17 12:13 UTC, jethror1 requested changes
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @JasonLing95, @jethror1, and @mattgarner)

___
*[helper.py, line 27 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtA7eDO3F68mqDD513J:-MtbvEqHENhkb9c0D8nU:bjsp1mv) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/helper.py#L27)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

everytime it runs, it will generate a new file with the filename dated.today() so that it's easier to track the log by day
</blockquote></details>

how many days of logs does it keep?
___
*[main.py, line 589 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtAEaBBBdHBSdb5JsqK:-MtbwXxb94YbKuhAk_xs:b-cicn92) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L589)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

commented just in case I accidentally ran the archiving api. In production this will be un-commented
</blockquote></details>

I guess you want to do this before I merge then?


<!-- Sent from Reviewable.io -->

2022-01-17 13:33 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[helper.py, line 27 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtA7eDO3F68mqDD513J:-MtcE7y7-IdWYTkkP_1t:b-w2l369) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/helper.py#L27)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

how many days of logs does it keep?
</blockquote></details>

it will generate log based on the datetime. e.g. dx-job-monitor, a new log dated daily will be generated whenever it runs
___
*[main.py, line 589 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtAEaBBBdHBSdb5JsqK:-MtcEJpn77ZUb4Cy4GMf:b-4f9chn) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/main.py#L589)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I guess you want to do this before I merge then?
</blockquote></details>

yes there will be a final push once everything is wrapped up to uncomment the code (just in case)


<!-- Sent from Reviewable.io -->

2022-01-18 14:18 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @JasonLing95 and @jethror1)

___
*[helper.py, line 27 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtA7eDO3F68mqDD513J:-MtgYkcw0qRRyr3mpfdX:b-ii8ek8) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/helper.py#L27)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

it will generate log based on the datetime. e.g. dx-job-monitor, a new log dated daily will be generated whenever it runs
</blockquote></details>

I guess for this it isn't too bad since it runs once per month (?), but I assume this doesn't have a max number of log files to keep? Probably more applicable for things running on a more frequent cron where it would be good to limit the amount kept


<!-- Sent from Reviewable.io -->

2022-01-18 14:28 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[helper.py, line 27 at r4](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtA7eDO3F68mqDD513J:-MthYpeA5_UytA--JR2R:b-hv27u4) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/19a091fca673034ef8b514bf251006b985232150/helper.py#L27)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I guess for this it isn't too bad since it runs once per month (?), but I assume this doesn't have a max number of log files to keep? Probably more applicable for things running on a more frequent cron where it would be good to limit the amount kept
</blockquote></details>

<how many days of logs does it keep?> one day. I was thinking running it every two weeks (people got two weeks to tag their projects before it being archived). 


<!-- Sent from Reviewable.io -->

2022-01-19 09:45 UTC, jethror1 requested changes
> Reviewed 2 of 5 files at r1, 1 of 3 files at r10, 1 of 1 files at r11, 1 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 5 of 7 files reviewed, 17 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[main.py, line 230 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtlfPXm00fA0TeayfuD:-MtlfPXm00fA0TeayfuE:bnqgf32) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L230)):*
> ```Python
> 
> 
> def check_dir(dir, month) -> bool:
> ```

does this discriminate between 003 and 002? I.e if there is an issue with a run we have made `003_{run_name}` projects before to run analysis to check things, would these be picked up the same? does this matter?
___
*[main.py, line 375 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtlgknW897JGxNWFi0f:-MtlgknW897JGxNWFi0g:b-5ib526) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L375)):*
> ```Python
>         **old_enough_projects_dict_002, **old_enough_projects_dict_003}
> 
>     excluded_list = [PROJECT_52, PROJECT_53]
> ```

references staging_area53



_Code quote:_
```Python
 PROJECT_53
```
___
*[main.py, line 377 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtlgntZ6wkePNHktire:-MtlgntZ6wkePNHktirf:b-5ib526) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L377)):*
> ```Python
>     excluded_list = [PROJECT_52, PROJECT_53]
> 
>     # exclude projs (staging52/53) and archived projs
> ```

references staging_area53



_Code quote:_
```Python
/53
```
___
*[main.py, line 388 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtlgiR80ICIV-idQPKC:-MtlgiR80ICIV-idQPKD:b-5ib526) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L388)):*
> ```Python
> def get_all_dirs(archive_dict, proj_52) -> list:
>     """
>     Function to get all directories in staging52 and 53
> ```

references staging_area53



_Code quote:_
```Python
and 53
```
___
*[main.py, line 439 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Mtlgw6b3qEp9yQw1ZpG:-Mtlgw6b3qEp9yQw1ZpH:b-5ib526) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L439)):*
> ```Python
> 
>     Input:
>         dir: directory in staging52/53
> ```

references staging_area53



_Code quote:_
```Python
53
```
___
*[main.py, line 478 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Mtlgz7_3bJ8hOjzQpjn:-Mtlgz7_3bJ8hOjzQpjo:b-5ib526) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L478)):*
> ```Python
> def find_projs_and_notify(archive_pickle):
>     """
>     Function to find projs or directories in staging52/53
> ```

references staging_area53



_Code quote:_
```Python
/53
```
___
*[main.py, line 487 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Mtlh1Ui2MO6eQHx7CJL:-Mtlh1Ui2MO6eQHx7CJM:b-5ib526) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L487)):*
> ```Python
>     dx_login()
> 
>     # special notify include those projs / directories in staging52/53
> ```

references staging_area53



_Code quote:_
```Python
/53
```
___
*[main.py, line 524 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtlhIiO8d1NVz9wa5SG:-MtlhIiO8d1NVz9wa5SH:b4wfec4) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L524)):*
> ```Python
>             # for Slack notification
> 
>             if 'never-archive' in tags:
> ```

do we log anywhere what projects and/or files have been tagged with `no-archive`? It might be good as a sanity thing to have these recorded so we know what isn't ever going to be archived (i.e if someone added the tag to not archive a project for a while, then never went back and removed it), I assume we won't often use this so could be added to the slack notification maybe for awareness?
___
*[main.py, line 539 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtlhhmxDaZ-5h41mPmT:-MtlhhmxDaZ-5h41mPmU:b-5ib526) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L539)):*
> ```Python
>                 to_be_archived_list.append(v['describe']['name'])
> 
>     # sieve through each directory in staging52/53
> ```

references staging_area53



_Code quote:_
```Python
/53
```
___
*[README.md, line 4 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Mtli5DD8L7he6TObHXj:-Mtli5DE3CkDnRWmU3Ws:b-5ib526) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/README.md#L4)):*
> ```Markdown
> 
> ## What does the script do
> Check for 002, 003 projects, directories in staging52 and staging53 which are not modified for the last X months (inactive). Compile all archivable into a list and send Slack notification to notify all to-be-archived files in the next run. Tag `no-archive` to skip archiving.
> ```

references staging_area53



_Code quote:_
```Markdown
staging53
```
___
*[README.md, line 13 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtliCIV4mQL3qK9snDb:-MtliCIV4mQL3qK9snDc:b-5ib526) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/README.md#L13)):*
> ```Markdown
> 
> ## Script Workflow
> When the script is executed, it checks if there's any 'to-be-archived' in its memory (to_be_archived, staging52, staging53). 
> ```

references staging_area53



_Code quote:_
```Markdown
staging53
```
___
*[README.md, line 18 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Mtli82t8SXvMuz5TlfD:-Mtli82u1gz_N28o1ame:b-5ib526) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/README.md#L18)):*
> ```Markdown
> to_be_archived = archive_pickle['to_be_archived']
> staging52 = archive_pickle['staging_52']
> staging53 = archive_pickle['staging_53']
> ```

references staging_area53



_Code quote:_
```Markdown
staging53 = archive_pickle['staging_53']
```
___
*[README.md, line 20 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtliDidDFwaayRz_aOb:-MtliDidDFwaayRz_aOc:b-5ib526) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/README.md#L20)):*
> ```Markdown
> staging53 = archive_pickle['staging_53']
> 
> if to_be_archived or staging52 or staging53:
> ```

references staging_area53



_Code quote:_
```Markdown
staging53
```
___
*[README.md, line 37 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtliHBm2y_cR3L2Z3wx:-MtliHBm2y_cR3L2Z3wy:bz792an) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/README.md#L37)):*
> ```Markdown
> - `PROJECT_52` : project-id
> - `PROJECT_53` : project-id
> - `AUTOMATED_MONTH_002` : Period of file being inactive after which to archive (months)
> ```

is the `_002` month just for 002 projects?
___
*[README.md, line 57 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtliLsx99mr_quZO1mi:-MtliLsx99mr_quZO1mj:b-5ib526) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/README.md#L57)):*
> ```Markdown
> 
> #### no-archive
> Projects tagged will temporarily bypass archiving. For directories in staging52 and staging53, if one or more files within a directory (`/210202_A12905_003`) is tagge [...]

2022-01-19 10:06 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 5 of 7 files reviewed, 17 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[main.py, line 230 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtlfPXm00fA0TeayfuD:-MtlkeIo3ScN-823g1WJ:b-n4yo7c) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L230)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this discriminate between 003 and 002? I.e if there is an issue with a run we have made `003_{run_name}` projects before to run analysis to check things, would these be picked up the same? does this matter?
</blockquote></details>

yes it will pick up either 003_<run name> or 002_<run name>
___
*[main.py, line 375 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtlgknW897JGxNWFi0f:-MtllQqn09V4NEg-U5UM:bxe08us) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L375)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

references staging_area53
</blockquote></details>

this is to exclude staging52 and staging53 from the old_enough_project (all projs which haven't been modified in last X month) so we don't accidentally include it in our archiving function, very unlikely since staging53 is constantly modified (have data uploaded to it), but just in case.
___
*[main.py, line 377 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtlgntZ6wkePNHktire:-MtlmZZs1RIRIenf5mSU:bim04no) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L377)):*
> this is to exclude staging52 and staging53 from the old_enough_project (all projs which haven't been modified in last X month) so we don't accidentally include it in our archiving function, very unlikely since staging53 is constantly modified (have data uploaded to it), but just in case.
___
*[main.py, line 388 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtlgiR80ICIV-idQPKC:-MtlmeAU831sbN7fYuXQ:b-hfpv0l) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L388)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

references staging_area53
</blockquote></details>

removed
___
*[main.py, line 439 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Mtlgw6b3qEp9yQw1ZpG:-MtlmmiL3rThSox9MEIR:b-hfpv0l) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L439)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

references staging_area53
</blockquote></details>

removed
___
*[main.py, line 478 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Mtlgz7_3bJ8hOjzQpjn:-Mtlmr5pAkd-cH1AASMt:b-hfpv0l) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L478)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

references staging_area53
</blockquote></details>

removed
___
*[main.py, line 487 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Mtlh1Ui2MO6eQHx7CJL:-MtlmupX2vG6eWUnWubQ:b-hfpv0l) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L487)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

references staging_area53
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2022-01-19 15:58 UTC, jethror1 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 5 of 7 files reviewed, 10 unresolved discussions (waiting on @JasonLing95 and @jethror1)



<!-- Sent from Reviewable.io -->

2022-01-19 16:05 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 5 of 7 files reviewed, 10 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[main.py, line 539 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtlhhmxDaZ-5h41mPmT:-Mtn3WYG070qFKt4J7fd:b-hfpv0l) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L539)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

references staging_area53
</blockquote></details>

removed
___
*[README.md, line 4 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Mtli5DD8L7he6TObHXj:-Mtn3Z8VCHn42_dXVC20:b-hfpv0l) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/README.md#L4)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

references staging_area53
</blockquote></details>

removed
___
*[README.md, line 13 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtliCIV4mQL3qK9snDb:-Mtn3_LT-hQ-UGtJJG1X:b-hfpv0l) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/README.md#L13)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

references staging_area53
</blockquote></details>

removed
___
*[README.md, line 18 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-Mtli82t8SXvMuz5TlfD:-Mtn3a5L1mmYJl012wgL:b-hfpv0l) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/README.md#L18)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

references staging_area53
</blockquote></details>

removed
___
*[README.md, line 20 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtliDidDFwaayRz_aOb:-Mtn3adc39ompXB544JI:b-hfpv0l) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/README.md#L20)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

references staging_area53
</blockquote></details>

removed
___
*[README.md, line 37 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtliHBm2y_cR3L2Z3wx:-Mtn3eWQ0_AiGhpEF5Qg:b121qm0) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/README.md#L37)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is the `_002` month just for 002 projects?
</blockquote></details>

yes it is (probably 6 months)
___
*[README.md, line 57 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtliLsx99mr_quZO1mi:-Mtn3lvZ2dc_yo28jXKZ:b-hfpv0l) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/README.md#L57)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

references staging_area53
</blockquote></details>

removed
___
*[README.md, line 62 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtliNB3Cl0qBLPoPoBK:-Mtn3nUYDT1nJBN6S1pN:b-hfpv0l) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/README.md#L62)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

references staging_area53
</blockquote></details>

removed
___
*[README.md, line 68 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtliOWTCQKIM-Oo1jqj:-Mtn3sUe4vyzWdf6UFhk:batmvsj) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/README.md#L68)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

references staging_area53
</blockquote></details>

I remember removing these references but why are they here hmmmmm


<!-- Sent from Reviewable.io -->

2022-01-19 18:13 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[main.py, line 524 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtlhIiO8d1NVz9wa5SG:-Mtn3CXIDVXIusTaBZne:buivnlx) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L524)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

do we log anywhere what projects and/or files have been tagged with `no-archive`? It might be good as a sanity thing to have these recorded so we know what isn't ever going to be archived (i.e if someone added the tag to not archive a project for a while, then never went back and removed it), I assume we won't often use this so could be added to the slack notification maybe for awareness?
</blockquote></details>

we currently don't log it anywhere. yes i think everytime it pings Slack, we could send a different section highlighting those tagged with no-archive and never-archive since i don't think the list is going to be too long. that way we don't need to go into the server to check if we ever want to know 

Currently added code: we will list all no-archive and never-archive projects in slack notification
However for directories in staging52 it's abit tricky because we don't query each objects within the directories to get their tag status so if the directory is outside of the old-enough / check_dir function (meaning they return False for the check_dir function), the script won't bother with them. We only query for tag status in the old-enough directory so the accuracy of no-archive and never-archive tag for directories in staging52 is kinda semi-accurate


<!-- Sent from Reviewable.io -->

2022-01-19 20:12 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[main.py, line 524 at r12](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-MtlhIiO8d1NVz9wa5SG:-Mtnxv3p8LxhVdRRDODP:b-ytttcj) ([raw file](https://github.com/eastgenomics/automated-archiving/blob/6f493b64cd4c4f7e1f10e7d0ee2871fa973418bb/main.py#L524)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

we currently don't log it anywhere. yes i think everytime it pings Slack, we could send a different section highlighting those tagged with no-archive and never-archive since i don't think the list is going to be too long. that way we don't need to go into the server to check if we ever want to know 

Currently added code: we will list all no-archive and never-archive projects in slack notification
However for directories in staging52 it's abit tricky because we don't query each objects within the directories to get their tag status so if the directory is outside of the old-enough / check_dir function (meaning they return False for the check_dir function), the script won't bother with them. We only query for tag status in the old-enough directory so the accuracy of no-archive and never-archive tag for directories in staging52 is kinda semi-accurate
</blockquote></details>

restructured the code. Added a new function get_tag_status and moved it to the end of get_proj_and_notify function.


<!-- Sent from Reviewable.io -->

2022-01-19 21:25 UTC, jethror1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1#-:-MtoDd6B4Rd1Y0C4F3qW:bnfp4nl)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-01-19 21:25 UTC, jethror1 approved these changes
> Reviewed 1 of 3 files at r10, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/automated-archiving/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)



<!-- Sent from Reviewable.io -->

2022-01-19 21:25 UTC, merged